[plot]
system = '''
あなたはプロの脚本家です。ジャンルに適した最高のストーリーを作ります
'''

makePlot = '''
以下のアイデアとジャンルをもとに、素晴らしいストーリーを作成し、筋書きのみを出力してください

## アイデア
${idea}

## ジャンル
${genres}

## 出力
'''

getCharacters = '''
そのストーリーに必要な登場人物一覧をjsonで出力してください
以下の情報を出力してください: 名前, 年齢, 性別, 性格, 役割 
{
    "characters": [
        {
            name: "キャラクターの名前",
            age: number,
            isMale: boolean,
            personality: string,
            role: string
        }
        ...
    ]
}
'''

[assignSprite]
system = '''
あなたはグラフィックデザイナーです。
'''

user = '''
あなたはキャラクター情報から適切な立ち絵を選択する必要があります。
性格等からどの立ち絵が最適であるかJSONで出力してください。
JSONには以下の例に則り、立ち絵IDのみを出力してください。

## JSON例
{
    "assign": [
        string,
        ...
    ]
}

## キャラクター情報
${characterInfo}

## 立ち絵IDと特徴
${spriteInfo}
'''

[makeScript]
system = '''
あなたはノベルゲームの脚本家です。userから提示される条件をもとに、特定の記法に従って脚本を記述してください。また、あなたはできる限り面白い脚本を出力する必要があります。
'''

user = '''
## ノベルゲームの内容
ユーザーによるストーリーの要望
${idea}

ストーリーのジャンルとして、以下のタグが与えられています
${genre}

あなたは、以下の内容を読み、ノベルゲームのストーリーおよび、セリフを考え、以下に記述している記法に従ってシナリオ"のみ"を出力してください。
必ず、シナリオは物語の終わりまで記述してください。
**シナリオは全体で200行にしてください**
シナリオは、起承転結で構成する必要がありますが、あなたの判断によって、従わないことができます。
**筋書きをもとにオリジナルシナリオを加え、一場面にあたる会話は多くして**
**シナリオにはキャラクターの性格や役割を大きく考慮してください。決して筋書きについてのみ書かないでください**

## 物語の筋書き
```
${plot}
```

## 登場人物の情報
以下は用意されている登場人物のidと名前、年齢、性別、性格、役割です。jsonで表記されています。
${characters}

## 背景画像
以下は用意されている背景画像のidと画像の説明(ex)です。jsonで表記されています
${background}

## BGM
以下は用意されているBGMのidと説明です。jsonで表記されています。
${music}

### 表情
ノベルゲームでは、登場人物の画像に表情が付きます。
表情を指定するには、idに続けてコロンと表情タグを記述します。(例: male1:sad)
表情タグには、以下の種類が存在します(jsonで表記されています)。
[
    "angry",
    "happy",
    "normal",
    "sad",
    "surprise"
]

## 記法
以下の記法に従ってシナリオを書いてください。
### 背景を変更する
[bg ここにid]

### 登場人物を表示
[show ここに表示したい登場人物のidと、それに続けて:表情を記述]

### 登場人物を非表示
[hide ここに非表示したい登場人物のid]

### BGMの再生
[bgm ここにBGMのid]

### 文章
文章は、一行に書いてください。
登場人物が喋る場合、一行をカギカッコ(「」)でくくり、先頭に登場人物のid(名前と間違えないように注意してください)を記述してください。

### 注意点
- スクリプトに関係ないもの（マークダウンなど）は出力しないようにしましょう。
- スクリプトのみを出力しましょう
- 存在しない背景を指定しないようにしましょう

## 例
以下は、上の記法を用いた例です。
[bg home]
male1「んん、ここは？」
目が覚めると、主人公は知らない場所にいた
[show female1:sad]
female1「やっと、起きましたか。」
[hide female1]

# 出力
'''

makeTitle = '''
この物語にふさわしいタイトルを考えてください
タイトル"のみ"を出力してください
'''